### ISSUE TITLE
AttributeError: 'Avatar' object has no attribute 'set_image_load_func'

### ISSUE THREAD

**Issue by dotlambda** [SeaDve/Mousai#17]
After updating to [libadwaita 1.0.0-alpha.1](https://gitlab.gnome.org/GNOME/libadwaita/-/tags/1.0.0-alpha.1), I get
```
Traceback (most recent call last):
  File "/nix/store/sy59jxn8ss9b913vz9pfp9r5r55hlzrp-mousai-0.4.1/share/mousai/mousai/main.py", line 60, in do_activate
    win = MainWindow(self.settings, application=self)
  File "/nix/store/sy59jxn8ss9b913vz9pfp9r5r55hlzrp-mousai-0.4.1/share/mousai/mousai/widgets/main_window.py", line 52, in __init__
    self.load_memory_list()
  File "/nix/store/sy59jxn8ss9b913vz9pfp9r5r55hlzrp-mousai-0.4.1/share/mousai/mousai/widgets/main_window.py", line 84, in load_memory_list
    self.new_song_row(song.values())
  File "/nix/store/sy59jxn8ss9b913vz9pfp9r5r55hlzrp-mousai-0.4.1/share/mousai/mousai/widgets/main_window.py", line 64, in new_song_row
    song_row = SongRow(*song)
  File "/nix/store/sy59jxn8ss9b913vz9pfp9r5r55hlzrp-mousai-0.4.1/share/mousai/mousai/widgets/song_row.py", line 40, in __init__
    self.song_icon.set_image_load_func(self.load_song_icon)
AttributeError: 'Avatar' object has no attribute 'set_image_load_func'
```
when running `mousai`.

**Comment by SeaDve** [comment]
I assume you installed it from the AUR. I think this is a packaging issue.

**Comment by SeaDve** [comment]
For now, I recommended downgrading or using flatpak version

**Comment by dotlambda** [comment]
Thanks a lot!
