### ISSUE TITLE
Cannot start in Arch Linux

### ISSUE THREAD

**Issue by tio-trom** [SeaDve/Mousai#32]
I get this error:
```
mousai
Traceback (most recent call last):
  File "/usr/sbin/mousai", line 30, in <module>
    from mousai import main
  File "/usr/share/mousai/mousai/main.py", line 18, in <module>
    class Application(Adw.Application):
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'Application'
```

Using Manjaro Gnome and installed it from here https://aur.archlinux.org/packages/mousai

**Comment by SeaDve** [comment]
that's likely the libadwaita version in aur is outdated, you can either use flatpak or contact mousai's maintainer in aur

**Comment by SeaDve** [comment]
I think I can close this since it is a packaging issue
